name = "ITK"
uuid = "c07c4cf6-b85e-11e9-2ee5-393f21797b38"
authors = ["Connor McLaughlin"]
version = "0.1.0"

[deps]
Cxx = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
